JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
	$(JC) $(JFLAGS) $*.java

CLASSES = \
	Puzzle.java \
	Move.java \
	Node.java
      

default: classes

classes: $(CLASSES:.java=.class)

clean:
	$(RM) *.class